### ISSUE TITLE
Regarding the mpv prescaler evaluation

### ISSUE THREAD

**Issue by bjin** [Artoriuz/artoriuz.github.io#1]
Thanks for doing this, it's always good to have a quantized comparison in addition to still-image screenshot comparisons.

However, I have a few questions and suggestions:
1. Could you evaluate `ravu-lite` variant in addition to the original `ravu`? There are a few points that makes a separated evaluation meaningful.
    * unlike `ravu`, `nnedi3` and `ngu-aa`, `ravu-lite` introduces no half-pixel offset. Which will make it a fair comparison to `ngu` and `fsrcnnx`.
    * `ravu-lite` is much faster. It uses a single pass and much fewer sampling points.
    * The sampling method is different between `ravu-lite` and `ravu`. It's interesting to know how they perform with the same `radius` setting.
2. The current evaluation is unfair to `ngu-aa`. I myself was also interested in its actual performance. While it might be impossible to fix the half-pixel offset in madVR, it's possible to fix the screenshot in mpv with mpv's built-in `--scale` via the following user shader. In this way, it will be a fair comparison to `nnedi3` and `ravu` at least (using the same mechanism to fix half-pixel offset).
~~~glsl
//!DESC add half-pixel offset
//!HOOK MAIN
//!BIND HOOKED
//!OFFSET -0.500000 -0.500000
vec4 hook() {
    return HOOKED_texOff(vec2(0.0,0.0));
}
~~~
3. How's the chroma upscaling evaluation conducted? I might be wrong, but I see a `jpeg` file in the folder and I assume it's the source file to be upscaled. But AFAIK `jpeg` is not lossless. Did you use a separated `yuv420` AVC lossless encoding? BTW the best practise I know to get a lossless `yuv420` image is a single frame yuv4mpeg (`.y4m`) file. It supports all common chroma subsampling location. It can be converted from any image with `ffmpeg`: `ffmpeg -i chroma444.png  -pix_fmt yuv420p -f yuv4mpegpipe chroma420.y4m`

**Comment by bjin** [comment]
4. Also, `ravu` and `nnedi3` are not CNN based. Both of them have trained weights by some machine learning techniques, but their model doesn't have deep architecture (`ravu` is single layer, and `nnedi3` has two layers). They also didn't use 2D Convolution layer like NGU and FSRCNN(X).

**Comment by Artoriuz** [comment]
Hi! Nice to see you active again =D

About your points, yes I can surely add ravu-lite to the mix. Fixing NGU-AA
in mpv is a great idea, I'll do it too as soon as I can.

When I wrote the chroma section, I tried going with CRF 0 (which according
to ffmpeg's documentation should be lossless) AVC like I had previously
done, but strangely enough the results from JPEG 100 were slightly higher.
Since whatever loss in place from the encoding was the same for every
scaler, I judged it fair enough, but doing it with yuv4mpeg is probably a
better idea, thanks for the suggestion.

I'll probably update the results later today, feel free to suggest anything
else!

**Comment by Artoriuz** [comment]
I tried to go with your ffmpeg suggestion but the y4m result seems to be
yellower than the original png, but it does seem "fixed" if I include -vf
colormatrix=bt601:bt709 but I don't think I should need to do this.

**Comment by bjin** [comment]
some additional comments:
1. I saw the performance chart and assumes you have `--no-scaler-resizes-only` option set for fps bench-marking (correct me if I'm wrong). It's unfair to all user shaders since two additional `--scale=spline36` passed will be inserted regardless of whether video offset is introduced by shader or not. Also, this option is not default and only useful for saving screenshots.
2. It's kind of weird to evaluate ravu-zoom with 2x upscaling, since only a tiny fraction of trained weights from ravu-zoom will actually be used for perfect 2x upscaling. If you are interested, maybe you can do another evaluation for 1.5x upscaling (addressing the common 720p video on 1080p screen case). ravu-zoom, SSSR and all built-in `--scale` are native to 1.5x upscaling. Other shaders (ravu, nnedi3, fsrcnnx, ngu) requires `--dscale`, which could just be the default one for `gpu-hq`. However, you should ensure the height and width of `reference.png` are multiple of 3, before generating `downscaled.png`, crop a few lines/columns if necessary.

**Comment by deus0ww** [comment]
If you're going to test 1.5x, could you also do 3x for 720p -> 4k? I've been trying to decide between FSRCNNX-3x and FSRCNNX-2x + RAVU-Zoom or SSSR.

**Comment by bjin** [comment]
since it's mentioned. Some comments on 3x upscaling:
1. ravu-zoom renders at upscaled resolution, so it's extremely slow for 3x upscaling. You probably want to use ravu-3x or ravu-lite twice instead.
2. there is no 3x variant for fsrcnnx, only for an old version of fsrcnn (which is deprecated I assume? @igv)
3. For all other prescalers, an fair comparison involves invoking the shader twice for 4x upscaling, then downscaled to 3x. Which could somehow be covered by 1.5x evaluation.

**Comment by bjin** [comment]
> I've been trying to decide between FSRCNNX-3x and FSRCNNX-2x + RAVU-Zoom or SSSR.

@deus0ww And ff you are going to use FSRCNNX (most likely the case). All you need is pick another shader for 1.5x upscaling.

**Comment by deus0ww** [comment]
There were versions of FRSCNNX with 3x and 4x but it seems like igv has removed them about 2-3 weeks ago with the last two quality retraining of 2x-16. It's a bit puzzling because I found them to be quite good, subjectively.

**Comment by igv** [comment]
3x and 4x were worse than 2x (much more aliased). 2x+SSSR or just plain lanczos is better.

I'd like also add that @Artoriuz uses PSNR-HA/HMA incorrectly, step has to be set to 7 (default is 8).

**Comment by Artoriuz** [comment]
I'd first like to say that I appreciate the feedback!

@bjin Yes I do have `--no-scaler-resizes-only` set for framerate benchmarks regardless of it being needed. I didn't originally think the performance impact was meaningful but I'll measure them again and update the chart.
Regarding the second point, I agree that my tests are underwhelmingly limited to a single scaling factor and 2 test images. It isn't a good representation of actual performance on different content, specially if you're not precisely doubling. 
I've been wanting to add different tests (like 720 -> 1080, which would be 1.5x) and different images (to properly represent anime that doesn't have line art as nice as Violet Evergarden), but I my current methodology consumes too much time and I always end up postponing it. 

Once I find some time I'll try to at least include a few relevant scenarios, 1.5x seems to be the perfect candidate since most still people have FHD displays.

@deus0ww 3x is complicated because there are simply too many different combinations, you can either double twice then dscale, or double once then upscale the rest using something else, or simply upscale directly to 3x using something that can do it like a normal built-in scaler or SSSR/Ravu-zoom.

@igv Thanks, I'll update it as soon as I can.

**Comment by Artoriuz** [comment]
@igv Would you mind explaining why wstep needs to be set to 7? 
I don't really have any knowledge about how the algorithm itself works, but setting it to 7 makes fsrcnnx score higher than waifu2x at shuri (the live action example), which at a first glance doesn't seem correct taking into consideration how they score against each other on any other measurement.

**Comment by igv** [comment]
This metric divides image into 8x8 blocks. By default they are non-overlapped most likely because it was tweaked primarily for noise and JPEG compression artifacts (which is also processes image in 8x8 non-overlapping blocks). In modern codecs everyone uses it with step 7 (e.g daala, VP9, [AV1](https://aomedia.googlesource.com/aom/+/refs/heads/master/aom_dsp/psnrhvs.c#253)).

**Comment by igv** [comment]
And on live action examples waifu2x can look worse than fsrcnnx because it over-enhances:
![ref](https://user-images.githubusercontent.com/16772957/56257985-a5a78d80-60d6-11e9-85f5-1b93177e6aa4.png)
reference

![fsrcnnx_x2_8-0-4-1](https://user-images.githubusercontent.com/16772957/56257963-97f20800-60d6-11e9-9256-9d5395a43d5c.png)
fsrcnnx_x2_8-0-4-1

![waifu2x](https://user-images.githubusercontent.com/16772957/56257978-a04a4300-60d6-11e9-83f8-68131a20d360.png)
waifu2x

**Comment by igv** [comment]
Look at this
![fsrcnnx_x2_8-0-4-1](https://user-images.githubusercontent.com/16772957/56289081-cc8eaf80-6128-11e9-9419-fbf62ebc09f6.png)
fsrcnnx_x2_8-0-4-1

![waifu2x](https://user-images.githubusercontent.com/16772957/56289088-d3b5bd80-6128-11e9-813c-53129d795ec4.png)
waifu2x

And there is more of aliasing artifacts like this with waifu. So yeah, pretty sure fsrcnnx is better than waifu2x for live action.

**Comment by Artoriuz** [comment]
Yeah, looks reasonable. Thanks. 

Gonna update the charts soon.

**Comment by deus0ww** [comment]
@igv On good sources, 2x + (Ravu Zoom, SSSR or lanzcos) is definitely better than 3x, subjectively. On not so great sources, 3x seems to be better at dealing with compression artifacts (especially in anime/cartoons). 

@bjin FSRCNNX_x2_16-0-4-1 + ravu-zoom-r4 + KrigBilateral is very very good. Ravu-zoom-r4 (gather) is a little slow, taking about 40-50% of the total time but it's worth it.
