### ISSUE TITLE
Testing fractional scaling > 2?

### ISSUE THREAD

**Issue by TheHardew** [Artoriuz/artoriuz.github.io#17]
For example, 480p -> 1080p is 2.25 times. You note on the website, that the choice of the scaler becomes less relevant as the scaling factor decreases. It'd be interesting to see how they all stack up at fractional scaling larger than 2.

**Comment by Artoriuz** [comment]
I think 2.25x is way too close to 2x, if I were to cover this it would probably be at 4x.

**Comment by Jules-A** [comment]
I'd be interested too, although there's not really many 4x scalers I know of. I just recently found out that FSR can be amazing above 2x, especially for medium level aliasing (which is the reason I considered a 4x scaler in the first place). I thought it was bad for aliasing before but it turns out due to the ported height/width it was actually downscaling from Ravu's 2x to my monitor's resolution...

Only problem is it doesn't play nice with noise and rings (more than it's inbuilt AR can handle above 2x) so you need Ravu with AR or some light denoiser/other shader + gpu-next's AR.

Actually I don't run it at 4x but ~2.6x (Ravu + set to 4x output) but if I wanted 4x and Ravu that would be a 16k image which is ironically due to FSR's speed, faster than my previous setup but such large textures actually causes MPV to lag on seek.
Also with such high scaling, FSR's RCAS seems to be less effective (even at max) so you'd need another instance of it or a sharper downscaler which I haven't looked into yet.

Testing it would probably be hard as generally you'd want a 4x scaler for lower res content (I've only tested it with 1080p with scaling above 2x (I currently use on 480p content after Ravu so only ~1.45x scaling there to my output res). If you are testing a 4x scaler do you test on low quality content which some are designed for or content perfectly downscaled?
