### ISSUE TITLE
Don't downscale in linear light

### ISSUE THREAD

**Issue by igv** [Artoriuz/artoriuz.github.io#6]
Compare SSSR or any scaler like spline36 before and after the violet upscaling remake. They are more aliased now.

Also why are you using such an old NR metrics? For example there is a newer version of NIQE called [IL-NIQE](http://www4.comp.polyu.edu.hk/~cslzhang/IQA/ILNIQE/ILNIQE.htm).
Or [BMPRI](https://drive.google.com/file/d/1C_NxTLvnBOJDGhqqtixCkra0LIMP6loF/view).
There is also a very good [deep learning based FR metric](http://civc.ucsb.edu/graphics/Papers/CVPR2018_PieAPP/) (windows executable available).

**Comment by Artoriuz** [comment]
To be honest with you I didn't intend to downscale in linear light anywhere
(and I think this is the only place where I fucked up, the subsequent
downscales for the other sections were all done in imagemagick). I left it
like that because I didn't think it would change the order of the scalers,
but I'll try to fix it today.

About NIQE, it's just for convenience. Matlab comes with it built in so
adding it to the mix was trivial. I'm trying to keep things simple this
time (so I'm able to update it more quickly) but if you have some
suggestions of good no-reference metrics with matlab implementations I'd be
happy to include them.

**Comment by Artoriuz** [comment]
It's updated now, no linear light downscaling anymore.
